# Build website with 11ty and sync to server
name: 11ty-build-and-deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ three-nav ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Build the site with 11ty
    - name: Eleventy Action
      uses: TartanLlama/actions-eleventy@v1.2
      with:
        # If set to `true`, `npm install` will be run before Eleventy is invoked
        install_dependencies: true

    # Deploy to github pages
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v1.1.0
      env:
        PUBLISH_DIR: _site
        PUBLISH_BRANCH: gh-pages
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
